### ISSUE TITLE
HDB/TDB archiving devices

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#15]
The archiving device servers should be running within dedicated docker container / image.
Image name should be `tangobox-archiving`. It should contain MariaDB for data.
Archiving package is available here: http://www.tango-controls.org/downloads/tools/
- [x] Download package, read included documenation
- [x] Database configured for HDB/TDB data
- [x] Running ArchivingManager
- [x] Running 2 HDB archiver device
- [x] Running 2 TDB archivier devcie
- [x] Runinng Watchers
- [x] Running Extractor

**Comment by stanislaw47** [comment]
What has been done by now
==================

Docker container with proper databases
--------------------------------------------

It has been pushed to repository with latest commit, but Dockerfile is still WIP. I need to add HDB/TDB++ related stuff, but for now, HDB and TDB are on the container.

Databases initialization and starting devices
------------------------------------------------

It is performed thanks to `supervisord`. It starts `initdb.sh` script and starts Tango Devices like `HdbArchiver`, etc. 

Container starts at system start-up
---------------------------------------

Just a single `systemd.service` presented below:

```
[Unit]
Description=Service for starting tangobox-archiving docker container
Requires=docker.socket
Requires=docker.service
Requires=tango-db.service
After=docker.socket
After=tango-db.service
After=docker.service

[Service]
ExecStartPre=/usr/bin/docker rm -f -v tangobox-archiving
ExecStart=/usr/bin/docker run -d --name tangobox-archiving -h tangobox-archiving --add-host TangoBox-VM:10.0.2.15 --restart=unless-stopped tangobox-archiving:latest

[Install]
WantedBy=multi-user.target
```
It has to be placed inside `/etc/systemd/system/`, then I just typed:
`sudo systemctl enable tango-archive.service` and that's it. Only problem is, there has to be container named `tangobox-archiving` on the machine.

New devices are registered at system start-up
--------------------------------------------------

Here is the part where I had biggest problems. To start with, I've placed this code inside `/etc/rc.local`
```
echo "Adding archiving devices"
echo "Adding sample HDBArchiver..."
mysql -u tango < /home/tango-cs/src/tangobox/docker/archiving/resources/sample1.sql

exit 0
```
However, normally `rc-local.service` starts before `mysql.service` so just add in `/etc/rc.local` following line in `[Unit]` section:
`After=mysql.service`

Next, I had to do this:
`sudo chmod 775 /etc/rc.local && sudo chown root /etc/rc.local`

**Comment by stanislaw47** [comment]
First of all, I have to manually start Device Server. I have no idea how to start them from Astor when they are run on a container.

Another thing, there is a problem with connection to database. For example, when I start `HdbArchiver` (from inside container, of cource), there is such output:
```
root@tangobox-archiving:/tmp/mambo/device/linux# ./HdbArchiver test 
./HdbArchiver: 22: ./HdbArchiver: [[: not found
./HdbArchiver: 30: ./HdbArchiver: [[: not found
2017-09-22 14:14:29.832  INFO test: HdbArchiver() create archiving/hdb/hdbarchiver.test
Seeing if events are enabled... (empty)
Looking in class properties (UseEvents)... (empty) false
The database priority is set to amt
2017-09-22 14:14:29.946  INFO test: HasThreadedStartup = true
isDedicated = false
reservedAttributes = []
diaryPath = /home/archivage/tango/hdbarchiver/diary/01
hasDiary = false
diaryLogLevel = DEBUG
#################
### Historic ###
#################
Host from Class Properties (HdbArchiver) : tangobox-archiving
Name from Class Properties (HdbArchiver) : hdb
Schema from Class Properties (HdbArchiver) : hdb
User from Device Properties : hdbarchiver
Password from Device Properties : hdbarchiver
Is Rac from Class Properties (HdbArchiver) : false
##########################
ConnectionFactory.connect: try Oracle hdbarchiver@hdb
ConnectionFactory.connect (Oracle): hdbarchiver@hdb KO
java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource
	at oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:541)
	at oracle.ucp.jdbc.PoolDataSourceImpl.throwSQLException(PoolDataSourceImpl.java:587)
	at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:276)
	at oracle.ucp.jdbc.PoolDataSourceImpl.setInitialPoolSize(PoolDataSourceImpl.java:1129)
	at fr.soleil.database.connection.OracleDataBaseConnector.createConnection(OracleDataBaseConnector.java:128)
	at fr.soleil.database.connection.AbstractDataBaseConnector.getNewConnection(AbstractDataBaseConnector.java:127)
	at fr.soleil.archiving.common.api.ConnectionFactory.testConnector(ConnectionFactory.java:244)
	at fr.soleil.archiving.common.api.ConnectionFactory.connect(ConnectionFactory.java:337)
	at fr.soleil.archiving.common.api.ConnectionFactory.connectThroughTango(ConnectionFactory.java:503)
	at HdbArchiver.Collector.DbProxy.<init>(DbProxy.java:166)
	at HdbArchiver.HdbArchiver.connectDatabase(HdbArchiver.java:631)
	at HdbArchiver.HdbArchiver.init_device(HdbArchiver.java:611)
	at HdbArchiver.HdbArchiver.<init>(HdbArchiver.java:548)
	at HdbArchiver.HdbArchiverClass.device_factory(HdbArchiverClass.java:296)
	at fr.esrf.TangoDs.DServer.init_device(DServer.java:217)
	at fr.esrf.TangoDs.DServer.<init>(DServer.java:112)
	at fr.esrf.TangoDs.DServerClass.device_factory(DServerClass.java:332)
	at fr.esrf.TangoDs.DServerClass.<init>(DServerClass.java:171)
	at fr.esrf.TangoDs.DServerClass.init(DServerClass.java:118)
	at fr.esrf.TangoDs.Util.server_init(Util.java:856)
	at HdbArchiver.HdbArchiver.main(HdbArchiver.java:1799)
Caused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:421)
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:389)
	at oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:105)
	at oracle.ucp.common.UniversalConnectionPoolImpl$UniversalConnectionPoolInternal.createOnePooledConnectionInternal(UniversalConnectionPoolImpl.java:1558)
	at oracle.ucp.common.UniversalConnectionPoolImpl$UniversalConnectionPoolInternal.access$600(UniversalConnectionPoolImpl.java:1366)
	at oracle.ucp.common.UniversalConnectionPoolImpl.createOnePooledConnection(UniversalConnectionPoolImpl.java:441)
	at oracle.ucp.common.UniversalConnectionPoolImpl.addNewConnections(UniversalConnectionPoolImpl.java:933)
	at oracle.ucp.common.UniversalConnectionPoolBase.getInitialConnections(UniversalConnectionPoolBase.java:607)
	at oracle.ucp.common.UniversalConnectionPoolBase.start(UniversalConnectionPoolBase.java:722)
	at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:270)
	... 18 more
Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:419)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:536)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:228)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:280)
	at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:207)
	at oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:99)
	... 25 more
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:375)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:422)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:678)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:238)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1054)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:308)
	... 32 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:209)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:123)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:353)
	... 37 more
2017-09-22 14:14:30.470 ERROR test: ERROR : Database unconnected !!
Message : IDL:Tango/DevFailed:1.0
	 [1] : 
		Reason : ArchivingException
		Severity : WARNING
		Description : Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource
		Origin : fr.soleil.archiving.common.api.ConnectionFactory.treatConnectionException(ConnectionFactory.java:136)

	at HdbArchiver.Collector.DbProxy.<init>(DbProxy.java:174)
	at HdbArchiver.HdbArchiver.connectDatabase(HdbArchiver.java:631)
	at HdbArchiver.HdbArchiver.init_device(HdbArchiver.java:611)
	at HdbArchiver.HdbArchiver.<init>(HdbArchiver.java:548)
	at HdbArchiver.HdbArchiverClass.device_factory(HdbArchiverClass.java:296)
	at fr.esrf.TangoDs.DServer.init_device(DServer.java:217)
	at fr.esrf.TangoDs.DServer.<init>(DServer.java:112)
	at fr.esrf.TangoDs.DServerClass.device_factory(DServerClass.java:332)
	at fr.esrf.TangoDs.DServerClass.<init>(DServerClass.java:171)
	at fr.esrf.TangoDs.DServerClass.init(DServerClass.java:118)
	at fr.esrf.TangoDs.Util.server_init(Util.java:856)
	at HdbArchiver.HdbArchiver.main(HdbArchiver.java:1799)
2017-09-22 14:14:30.481 DEBUG test: init done
Ready to accept request
```

I've been told that creating another property, `DbType` and setting it to `MySQL` would solve the problem but this seems to take no effect. Look at the `ConnectionFactory.connect: try Oracle hdbarchiver@hdb`, it seems to me that `HdbArchiver` tries to connect with Oracle database. I docs, it is written that without `DbType`, device will try to connect to Oracle, and then to MySQL. 

I have virtually no idea what is wrong. Maybe there's a mess in my `tango` database but I've cleared it and there was no difference.
@andygotz, @chedburgh, @Ingvord, @sergirubio, are you able to help me with that issue?
I also noticed user with **girardot** nickname on Tango Controls Forum, who seems to be in the know with HDB/TDB.

**Comment by andygotz** [comment]
I have contacted Raphael Girardot of Soleil. I hope he has time to help.

**Comment by andygotz** [comment]
Raphael sent me two comments:

1. you should set DbType tp "MySQL"
2. make sure the MySQL / MariaDB is configured to access remote access in case HDB is not running on same machine as MySQL / MariaDB. Some more tips are provided here:

http://www.tango-controls.org/community/forum/c/general/installation/snaparchiver-execution-error/

**Comment by stanislaw47** [comment]
Thank you @andygotz.
I've set `DbType` to "MySQL inside my sampl.sql file, it is in my Tango database. However, it cannot be reached by HdbArchiver class, somehow. Had to do this manually. After that, I'm receiving this error:
```
Reason: ArchivingException
Severity: WARNING
Desrciption: access denied for user 'browser@localhost' (using password: YES)
Origin: fr.soleil.archiving.common.api.ConnectionFactory.treatConnectionFactory(ConnectionFactory.java:144)
```

**Comment by piogor** [comment]
It looks like problem with  user credential settings – it uses username `browser` not `hdbarchiver`.

**Comment by stanislaw47** [comment]
Now I have a problem with HdbExtractor, it says that 
```
Client does not support authentication protocol requested by server; consider upgrading MariaDB client
```

However, it's the only server which has a problem with that, other HDBs are running fine

**Comment by stanislaw47** [comment]
I've figured out that this error occurs on every TDB or HDB device server. However, only in case of Archiving Watcher it causes them to fail. On the other hand, Extractors are starting endlessly. Every other device server is green and running. @andygotz can you contact Raphael again?

**Comment by stanislaw47** [comment]
Ok, problem solved, device servers are running smotohly
