### ISSUE TITLE
TangoBox 9.2RC11 - jhdbviewer error when trying to add an attribute to the query

### ISSUE THREAD

**Issue by bourtemb** [3Controls/tangobox#77]
The following error occurs when double-clicking on an attribute (sys/tg_test/1/ampli for instance) on jhdbviewer tree.
This error can be seen when starting jhdbviewer from the command line:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.tango.jhdb.HdbReader.getSigInfo(Ljava/lang/String;I)Lorg/tango/jhdb/HdbSigInfo;
	at HDBViewer.HDBTreePanel.attributeAction(HDBTreePanel.java:151)
	at HDBViewer.AttributeTree.TreePanel.fireTreeListener(TreePanel.java:411)
	at HDBViewer.AttributeTree.TreePanel.mousePressed(TreePanel.java:449)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Here is the CLASSPATH displayed:
`CLASSPATH /usr/local/share/java/JTango.jar:/usr/local/share/java/ATKWidget.jar:/usr/local/share/java/ATKCore.jar:/usr/local/share/java/jhdbviewer-1.13.jar:/usr/local/share/java/HDB++-1.10.jar:/usr/local/share/java/jcalendar-1.4.jar:/usr/local/share/java/jython-standalone-2.7.0.jar`

**Comment by piogor** [comment]
Thank you @bourtemb for reporting, the issue will be solved as part of new release in preparation in tango-controls fork (https://github.com/tango-controls/tangobox)
